.TH osc2midi 1
.SH NAME
osc2midi \- A bridge between OSC and (ALSA) MIDI. (see https://github.com/BlokasLabs/osc2midi/ for more information).
.SH SYNOPSIS
.B osc2midi "Virtual Port Name" host_ip host_port

Example:

osc2midi "Osc MIDI Bridge" 127.0.0.1 8000
.SH DESCRIPTION
.B osc2midi
A bridge between OSC and (ALSA) MIDI.
